annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: 8E9B315F6C22E339959DA77B35CCF4BDC9F58F2A
    url: https://openfga.github.io/helm-charts/pgp-public-key.asc
apiVersion: v2
appVersion: v1.8.16
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.12.10
- condition: mysql.enabled
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 9.6.0
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.13.3
description: A Kubernetes Helm chart for the OpenFGA project.
home: https://openfga.github.io/helm-charts
icon: https://github.com/openfga/community/raw/main/brand-assets/icon/color/openfga-icon-color.svg
name: openfga
type: application
version: 0.2.35
