apiVersion: v2
appVersion: 0.9.3
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.7.26
- alias: openfga
  condition: internalOpenFGA
  name: openfga
  repository: https://openfga.github.io/helm-charts
  version: 0.2.35
description: Helm Chart for Lakekeeper - a rust native Iceberg Rest Catalog
home: https://github.com/lakekeeper/lakekeeper
icon: https://raw.githubusercontent.com/lakekeeper/lakekeeper/refs/heads/main/site/docs/assets/bear.svg
keywords:
- lakekeeper
- iceberg
- catalog
- rest
- lakehouse
maintainers:
- name: Christian
  url: https://github.com/c-thiel
name: lakekeeper
type: application
version: 0.7.1
